### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by vikramdurai**
Docs are generated from code, so change code to meet ES6 standards

### CODE REVIEW

**Comment by jbielick** [comment]
Could you run the gulp task for generating the docs as well? `./node_modules/.bin/gulp docs`

**Comment by vikramdurai** [comment]
Finished?

**Comment by jbielick** [comment]
Thanks!

**Comment by wachunei** [comment]
Docs are missing this feature https://github.com/alexmingoia/koa-router/pull/396

**Comment by vikramdurai** [comment]
Sure (leaves less work for me then. got to sleep.)

**Comment by wachunei** [comment]
@vikramdurai got ya covered #418 😉

**Pull request merged**
