### PR TITLE
Fixes issue when no routes are matched Router.prototype.use with no URL will not work

### PR DESCRIPTION
**Pull request by divmgl**
Addresses issue #161

### CODE REVIEW

**Comment by kudos** [comment]
@alexmingoia Any sign of this getting merged? Looks like if no routes are explicitly matched the router's middleware does not get called.

**Comment by divmgl** [comment]
After further investigation, the OP of issue #161 is doing something incorrectly because his code actually works in the master branch. However, as @kudos mentioned, if no routes are explicitly matched no other middleware gets called. This pull request will allow for configurations like this:


```js
var serve = require('koa-static');
var router = new require('koa-router')();

router.use(serve('/../public'));

[
  '/customer',
  '/customer/:id'
].forEach(function(route){
  router.use(rewrite(route, "/"));
});

app.use(router.middleware());
app.listen(80);
```

**Comment by alexmingoia** [comment]
This should be fixed in `5.2.1` please confirm.

**Comment by kudos** [comment]
Fixed for me in `5.2.1`. Thanks!

**Pull request closed without merging**
