### PR TITLE
make README.md more clear

### PR DESCRIPTION
**Pull request by zzuieliyaoli**
I'm sorry to say that, but the demo codes made me confused.

I run codes as showing below:
```js
var app = require('koa')();
var router = require('koa-router')();
```
The output is:

```
const app = require('koa')()
                          ^
TypeError: Class constructor Application cannot be invoked without 'new'
```
I tried many times and spent much time finding how to run demo codes successfully.

That's hard work for me, but I still solved it finally.

```js
var Koa = require('koa');
var Router = require('koa-router');

var app = new Koa();
var router = new Router();
```

So, I hope that this PR can help somebody else.

### CODE REVIEW

**Comment by jbielick** [comment]
Thanks!

**Comment by kswope** [comment]
Almost a year later and I had to go through the same pain as original poster, whats up?

**Comment by jbielick** [comment]
@kswope what is your question?

**Comment by kswope** [comment]
no question, zzuieliyaoli discovered an error with the docs, fixed it, but they are unchanged.

**Comment by jbielick** [comment]
You might be looking at the wrong branch. The default branch for this repo on github is the `5.x` branch, which is outdated. This PR was merged into `master`. Unfortunately I don't have the ability to change the default branch so the old readme shows up by default on github when you visit this repo.

**Comment by kswope** [comment]
Oh yea, what a mess.  Its not that I *might* be looking at the wrong branch, google brings you right there if you google koa-router.  I'm be surprised if a single person was looking at the right branch.  Did you try this? https://help.github.com/articles/setting-the-default-branch/

**Comment by jbielick** [comment]
> Unfortunately I don't have the ability to change the default branch

**Comment by kswope** [comment]
Oh ok.  I hopefully somebody in charge will see this and same some future users some hassles.  Makes me wonder if I should stay away from koa since an essential middleware doesn't even have the maintainers to display the correct docs.

**Pull request merged**
