### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by lagden**
✗ Low severity vulnerability found on debug@2.6.8
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:debug:20170905
- from: koa-router@7.2.1 > debug@2.6.8
Your dependencies are out of date, otherwise you would be using a newer debug than debug@2.6.8.

### CODE REVIEW

**Comment by lagden** [comment]
I did some updates...
That problem is breaking my CI!!

**Comment by jbielick** [comment]
Could this PR include _just_ the upgrade of `debug` and not everything else?

**Comment by lagden** [comment]
Sure!!

**Comment by jbielick** [comment]
Thanks!

**Pull request merged**
