### PR TITLE
Support named routes with RegExp when using .all() method

### PR DESCRIPTION
**Pull request by MartinKolarik**
Adds the same check that is used [here](https://github.com/MartinKolarik/koa-router/blob/7b77a3e0d5a2b99817330ed5adf852705e3d5959/lib/router.js#L194).

### CODE REVIEW

**Comment by jbielick** [comment]
I'm -1 on this. Passing regexp arguments to route methods isn't documented—that's why this method doesn't already accept regular expressions.

**Comment by MartinKolarik** [comment]
But all other methods do support RegExp arguments, why should this one be different?

**Comment by jbielick** [comment]
I can't say for sure because I'm not the original author, but most or all of this libraries code assumes `path` or `prefix` arguments to all of the routing methods is a string. This library uses path-to-regex to turn _all paths (strings) into regexs_ for route matching. Even that library mentions it should be receiving strings. The fact that you _can_ pass a regex and it works on _some_ cases seems incidental to me. Im not sure some of the functionality of this library even works when you pass a regex in (prefixes, nested routers, param matching), so modifying the code to explicitly allow a regex in *one* part of the library without regard to the others essentailly opens this library up to an array of new issues and complaints as it wasn't originally written to support that. 

I could be wrong about only accepting strings, but the code makes that assumption in a few places—not just this method you've modified. The docs also do not mention passing in a regex and neither does the path-to-regex docs to my knowledge. 

"Support regex" seems to only be a partial truth and incidental. Does that make sense?

**Comment by MartinKolarik** [comment]
I understand that some features might not work with regexes, and that's a fair trade-off imho. What I meant by "all other methods support regexes" it that there already is an explicit check for this very thing: https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L194 but `.all()` method is handled in a different place than other `.verb()` methods, and doesn't have this check.

There are also [tests for regex paths, including nested routes](https://github.com/alexmingoia/koa-router/blob/master/test/lib/router.js#L134) so I definitely would call it incidental.

**Comment by jbielick** [comment]
You're right, _accidental_ is probably the better word.

Those are good examples:

Re: `path instance of Regexp`. This was not written by the original author. It was merged without any discussion about what it would break or what issues it would cause down the road and [the PR](https://github.com/alexmingoia/koa-router/pull/152) only intended on fixing a bug someone had _as a result of the library not supporting regexs from the beginning.

https://github.com/alexmingoia/koa-router/commit/e8e2b5e4f7dfeb4bd48b8b411369be992c26b1bd

Re: "does not break when nested-routes use regexp paths"

**Comment by jbielick** [comment]
If you wrote better tests for this (make a request, assert that it matches) I would be more comfortable merging. I can see your argument for consistency with the other methods, but this test case is not valuable and doesn't assert that a regex path even works when routing. I realize it looks like the older tests "registers route with a regexp path", but those are also really poor.

**Pull request closed without merging**
