### PR TITLE
Add support for path prefixes.

### PR DESCRIPTION
**Pull request by nicholaswyoung**
This is a basic implementation of the functionality requested in #105. You might be able to improve upon it, but I think this satisfies the main requirements.

**Update:**

Added ```Router#prefix``` as a convenience method.

### CODE REVIEW

**Comment by nicholaswyoung** [comment]
@alexmingoia Do you have any comments on this?

**Comment by alexmingoia** [comment]
At first glance this lacks support for prefixing routes with regex path patterns. I will have time to look at this this week.

**Comment by nicholaswyoung** [comment]
Yeah, I realized it was missing after I built the PR. Do you have a handy method for concatenating regexes? If so, I can add it.

**Comment by nicholaswyoung** [comment]
@alexmingoia Just added prefixing for Regular expressions too. I think this resolves our earlier issue.

**Comment by nicholaswyoung** [comment]
@alexmingoia Any word on when this might be integrated?

**Comment by alexmingoia** [comment]
This is included in 4.3.0 but I made a couple of changes. Router#setPrefix() was moved to Route#setPrefix() and Router#prefix() updates existing routes in addition to setting the prefix.

**Comment by nicholaswyoung** [comment]
@alexmingoia Excellent!

**Pull request merged**
