### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by sansSpoon**
Hi guys, I’m totally new to Koa and Koa-router (and pull requests), so please excuse my ignorance. While attempting to understand Koa-router, I found the readme to be somewhat confusing and hard to read. While learning, I’ve done some minor adjustments to the layout so it reads better with Github’s limited markdown styles. I also have some additional comments below, that will need to be reviewed by someone with a better understanding of the module. I’ll happily update the doc’s further based on feedback.

-	router.verb
	-	type block mentions callback, but callback isn’t described anywhere
	-	not sure if “path” should be bracketed in the usage string. As far as I know it’s not optional?

-	router.routes
	-	This needs a much better explanation and examples. I’m still lost on why this is needed and how to use it best. Looking over some of the issues, I’m not the only one. From what I can gather this also pretty essential for every use of a Router instance.
	-	Maybe this needs to be listed 2nd, after `new Router`?
	-	Is it a property, or a method?

-	router.route(name)
	-	does this query a give name, and return the name if found, else return the string “false”?
	-	an example might be good here.

Regards
David

### CODE REVIEW

**Comment by jbielick** [comment]
Hi @sansSpoon!

Thanks for looking into this and your thorough review. I see that you've modified the readme in your PR and I think that might present some problems because the readme is _programatically generated_ by jsdoc. The readme template is in the repo. Most of the readme is generated from comments in the source code, so to change the content you should change the comments in the source. Otherwise your changes will get overwritten the next time we generate the docs. Does that make sense? See the package.json for a task named "docs" and the command to generate them is there.

**Comment by sansSpoon** [comment]
OK, thanks for explaining that. I’ll look into how the docs are generated.

Can you comment on any of the questions I made?


Regards
David

**Comment by jbielick** [comment]
> type block mentions callback, but callback isn’t described anywhere

seems out of date / wrong.

> not sure if “path” should be bracketed in the usage string. As far as I know it’s not optional?

it is not optional. Something about the way its documented in the code (comments above the method) are causing jsdoc to document it that way.

> This needs a much better explanation and examples. I’m still lost on why this is needed and how to use it best. Looking over some of the issues, I’m not the only one. From what I can gather this also pretty essential for every use of a Router instance.

I don't recall a lot of issues asking about why `routes()` is necessary, but have at it and add some docs if you feel like it isn't clear enough.

> Is it a property, or a method?

It says `function`. Did you see it used as a property somewhere?

screen shot 2018-03-01 at 10 07 52 pm

> does this query a give name, and return the name if found, else return the string “false”?
an example might be good here.

screen shot 2018-03-01 at 10 09 58 pm

That's a pretty safe assumption. It says it takes a name (`String`) and the `=>` indicates the return value types which are `Layer` or `false`. `false` is probably what it returns when no route is found. Again, have at it—can't hear to add some more notes.

**Comment by jbielick** [comment]
Please reopen when you have a chance to take a look at the last comment here!

**Pull request closed without merging**
